### PR TITLE
Added non 200 validation for URLfield in homework/project submissions

### PR DESCRIPTION
**Pull request by alex-kolmakov**
Added the field validation directly to the model and expanded tests in test_data.py to:

1. Run validation on basic data creation.
2. Added 2 tests to assert that ValidationError was raised if link leading to 404 was present.

Used [httpbin](httpbin.org) for 404 imitation.

### CODE REVIEW

**Comment by alex-kolmakov** [comment]
Now URL submission links for homework/project and learning in public links should return 200 and otherwise will look like:
Screenshot 2024-07-30 at 3 00 07 PM
Screenshot 2024-07-30 at 2 58 56 PM

**Comment by alex-kolmakov** [comment]
@alexeygrigorev checked locally and adjusted tests.
Please verify when able.

**Comment by alexeygrigorev** [comment]
Amazing, thank you! I adjusted the code slightly by adding a few more tests - and also django wanted to modify the migration code. Merging right now and deploying!

**Comment by alexeygrigorev** [comment]
image
awesome! deployed

**Comment by alex-kolmakov** [comment]
> Amazing, thank you! I adjusted the code slightly by adding a few more tests - and also django wanted to modify the migration code. Merging right now and deploying!

Glad I could help out! And thank you for adding nice touch on github links!

**Pull request merged**
